### ISSUE TITLE
Auth Portal integration

### ISSUE THREAD

**Issue by gedw99** [jr200/nats-iam-broker#1] opened 2024-08-11 04:43 UTC
https://github.com/authelia/oidc-tester-app might be useful to replace the third party one that is used. I have not tested integration yet.

Also, Authelia provides an auth portal and can pass the token to caddy or other proxies and so on to nats-iam-broker. I have not tested it yet.

Authelia has its own storage system as there is a lot going on in Ted s of workflows and data .

anyways my intention with this issue is to raise the idea of auth portals .

**Comment by jr200** [comment] 2024-08-11 08:12
I used https://oidctest.wsweet.org/ because it was the quickest thing to get up and running - I'm certainly not committed to it. Are you saying theres some oidc workflow(s) that isnt currently working due to some limitations of the mock auth provider I've chosen - that is supported by authelia's oidc tester app? If so, could you let me know whats missing?

I use authentik in my setup. I'm not very familiar with authelia. Are you saying the microservice is currently not compatible with authelia? 

Its meant to be quite a simple service which just accepts a JWT token passed in from the nats connect command. I havent understood how authelia portals or authelia's storage system interacts with nats-iam-broker. 

Theres certainly scope for expansion of functionality, but I havent quite grasped what the issue is. Could you flesh out your example pls.

Thanks!

**Comment by jr200** [comment] 2024-08-11 09:02
As long as the third-party auth provider is OIDC connect compliant, it should work with nats-iam-broker. This means you should be able to plumb in any provider you want: auth0, google, authelia, keycloak, pocketbase.... You only need to pass a non-expired JWT obtained from your third-party auth-provider into the password field of the nats connect command, and the nats-iam-broker microservice should be able to swap that for a nats user JWT.

Its also not clear to me how you would use the forward proxy flow to interface with nats server, or what the benefits of doing this are. But I have quite a specific use-case for nats too...

**Comment by jr200** [comment] 2024-08-11 09:32
I see! Ok then perhaps I need to improve my documentation slightly.

Once you authenticate with your OIDC-compliant auth provider, you'll get back an id_token (this is a short-lived token that will normally expire in ~1h or <24h). This is the jwt you want to use in the nats connect command. Have a look at `examples/basic/basic_simulate_login.sh`.

```bash
JWT_DWHO=`idp_mock_login_public dwho dwho`
test-client \
    -url=${NATS_URL} \
    -creds=${SECRET_STORE}/MINT/user-nobody.creds \
    -jwt $JWT_DWHO \
    -run-test "pubsub basic.public.ZHdobw== hello-from-dwho"
```


The first line simulates you the login process with your chosen oidc provider and you get back an id_token JWT. That jwt is passed to the `test-client` which does:

```golang
nc, err := nats.Connect(
    natsURL,
    nats.UserCredentials(credsFile),
    nats.UserInfo("jwt", idpJwt),
)
```

Notice the username=`"jwt"`, password=`idpJwt`.

The test-client is a minimal app which simulates what you would do in your real application to connect to nats.

**Comment by jr200** [comment] 2024-08-14 07:45
> https://github.com/zitadel/oidc Is the oidc client and server .

Oh I hadn't heard of zitadel, but it does look lightweight. I agree that a more complete example would help. I'm currently working on writing a helm-chart for this, and also getting that to work with vault/openbao.

After that, I'll do a minimal javascript/react example - though I might put that example in a separate repo. Will keep you posted. Thanks for your feedback @gedw99

**Closed** 2024-09-09 09:32 UTC
